MGR_ENDPOINT:
  http://dashboard.rook.221.154.134.31.traefik.me:10017
RGW_ENDPOINT:
  http://object-storage.rook.221.154.134.31.traefik.me:10017
RGW_ADMIN_ACCESS:
  sodas_dev_access
RGW_ADMIN_SECRET:
  sodas_dev_secret
RGW_ADMIN_UID:
  sodas_dev_user

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: list
    tags-sorter: alpha
    operationsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true

keycloak:
  realm: master-i
  authServerUrl: http://keycloak.221.154.134.31.traefik.me:10017/
  sslRequired: none
  resource: platform
  credentials:
    secret: ae46ef1b-f7bc-47db-8096-d821ffb999e1
  confidentialPort: 0