MGR_ENDPOINT:
  http://dashboard.rook.221.154.134.31.traefik.me:10017
RGW_ENDPOINT:
  http://object-storage.rook.221.154.134.31.traefik.me:10017
RGW_ADMIN_ACCESS:
  sodas_dev_access
RGW_ADMIN_SECRET:
  sodas_dev_secret
RGW_ADMIN_UID:
  sodas_dev_user

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: list
    tags-sorter: alpha
    operationsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true

keycloak:
  realm: Master-i
  auth-server-url: http://keycloak.221.154.134.31.traefik.me:10017/
  ssl-required: none
  resource: platform
  credentials:
    secret: ae46ef1b-f7bc-47db-8096-d821ffb999e1
  confidential-port: 0

#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://keycloak.221.154.134.31.traefik.me:10017/auth/realms/MSA
#        registration:
#          keycloak:
#            #            provider: keycloak
#            client-id: platform
#            client-secret: ae46ef1b-f7bc-47db-8096-d821ffb999e1
#            authorization-grant-type: authorization_code
#            redirect-uri: 'http://localhost:8080/login/oauth2/code/keycloak'
#
#  keycloak:
#    realm: MSA
#    #  public-client: false
#    resource: spring-gateway-client
#    auth-server-url: http://keycloak.221.154.134.31.traefik.me:10017/auth
